export const defaultMovies = [
  "The King's Speech",
  "The Hateful Eight",
  "Jojo Rabbit",
  "District 9",
  "The Green Mile",
  "Jobs",
  "Chappie",
  "Pacific Rim",
  "All Quiet on the Western Front",
  "Oldboy",
  "Rush Hour",
  "The Wild Robot",
  "Kung Fury",
  "Astartes",
  "The Hobbit: The Battle of the Five Armies",
  "The Intouchables",
  "TRON: Legacy",
  "Puss in Boots: The Last Wish",
  "1917",
  "Bridge of Spies",
];
